//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberConnectProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int AdminID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PasswordID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> BarberID { get; set; }
    
        public virtual Administrator Administrator1 { get; set; }
        public virtual Barber Barber { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual LocationInfo LocationInfo { get; set; }
        public virtual SelectionPage SelectionPage { get; set; }
    }
}
