//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberConnectProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BARBERCONNECT_APPEntities : DbContext
    {
        public BARBERCONNECT_APPEntities()
            : base("name=BARBERCONNECT_APPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Barber> Barbers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LocationInfo> LocationInfoes { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<SelectionPage> SelectionPages { get; set; }
    }
}
